### PR TITLE
removed a segfault causing instruction

### PR DESCRIPTION
**Pull request by cjwagenius**

### CODE REVIEW

**Comment by martinwguy** [comment]
Many thanks. I will look into this in the next few days

Blessings

   M

**Comment by martinwguy** [comment]
Hi again. Do you have a way to provoke the segfault you mention, just to verify it?

Also, there is a difference in functionality with the str[n]cpy change, in that the old code doesn't copy the final nul, whereas the new one does, though it's not clear to me whether this is harmless or not.

Thanks once more

    M

**Comment by cjwagenius** [comment]
Hmmm... It will probably not segfault. I was thinking of null, but the memory is only freed. Should not write to freed memory though.

Regards
Cjw

25 juli 2019 14:48 av notifications@github.com:

**Comment by martinwguy** [comment]
> On 25/07/2019, C.J.Wagenius <notifications@github.com> wrote:
>> Hmmm... It will probably not segfault. I was thinking of null, but the
>> memory is only freed. Should not write to freed memory though.

For sure. I'll see if I can figure out what it's trying to achieve in
that fragment, and check for possible writes to freed memory.

Thanks again

    M

**Comment by martinwguy** [comment]
PS Sorry about the quoted reply. Hit the wrong button...

Bless

   M

**Comment by cjwagenius** [comment]
In line 169 inbuf is getting freed and in 172 a null-char is being written to it.

**Comment by cjwagenius** [comment]
in screen:311 s is being set to NULL which will get strlen/strncpy/strcpy to segfault.

**Pull request merged**
