### PR TITLE
Prevent last char from being cleared.

### PR DESCRIPTION
**Pull request by jvvv**
Fix for issue #24.

### CODE REVIEW

**Comment by martinwguy** [comment]
This does seem to fix the described bug but introduces another.
Repeat-by: In an 80-column window_ xvi[Enter]80aa[Esc]
Only 79 a's are displayed with a space in the last position (the last a is there really in the buffer)

**Comment by jvvv** [comment]
Interesting enough, I just tried this commit on top of my issue35 branch and this side affect seems to absent.

**Comment by jvvv** [comment]
Or I could simply push the changes in the issue35 branch onto issue24_fix branch. This would pull those commits into this pr.

**Comment by martinwguy** [comment]
Whatever is fine.  Just let me know what I have to test.
Your attention is very welcome! xvi is very happy for the love it's receiving!

   M

**Comment by jvvv** [comment]
Ok, fair enough.

**Comment by jvvv** [comment]
I removed the initial commit that I started with for this branch. Its change was only reacting to the effects of https://github.com/jvvv/xvi/commit/1647a98b51be48d61662c251fd9cf60faef227b1.

**Comment by jvvv** [comment]
Well, this pr is not working... I need to spend more time on both #24 and #35... it's obvious they are interrelated; one patch addressing part of the symtoms ends up having negative impact on other parts. I'll leave exist, may even commit to it or rebase it, but this pr needs to be closed until I get closer to viable solution. Apologies for the noise.

**Pull request closed without merging**
