### PR TITLE
Fixes for issue #42

### PR DESCRIPTION
**Pull request by jvvv**
When resizing windows due to reduction of screen size, if the
screen size is smaller than the set minimum, then
xvAdjustWindows tries to set the curwin to the last window...
add a check that the last window (other than current window)
is valid before assigning it to curwin.

### CODE REVIEW

**Comment by jvvv** [comment]
This addresses #42. It is possible that more review of the xvAdjustWindows routine is called for. This can be revisited later if it is deemed that window resizing needs attention. At least this prevents the segfault.

**Comment by martinwguy** [comment]
It does, but I notice that the status line disappears while the window is 2 high, replaced by a ~ and if you then go ^G hoping to refresh the status line, you get a different segfault:
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x08057890 in do_sline (win=0x8097468) at screen.c:294
294		*to++ = *from++;
(gdb) bt
#0  0x08057890 in do_sline (win=0x8097468) at screen.c:294
#1  0x08057813 in update_sline (win=0x8097468) at screen.c:269
#2  0x0805a245 in show_file_info (window=0x8097468, show_numbers=0)
    at status.c:125
#3  0x0805cc23 in do_cmd (cmd=0x80974e0) at vi_cmds.c:41
#4  0x08053e5a in HandleCommand (cmd=0x80974e0) at normal.c:238
#5  0x08053c35 in normal (c=7) at normal.c:148
#6  0x0804f478 in n_proc (c=7) at events.c:244
#7  0x0804f337 in xvi_handle_event (ev=0xbfd410f0) at events.c:179
#8  0x080610eb in tcap_scr_main (argc=1, argv=0xbfd411e4) at tcap_scr.c:355
#9  0x08060eb4 in main (argc=1, argv=0xbfd411e4) at tcapmain.c:31

**Comment by martinwguy** [comment]
Same symptoms with this and the "Account for statusline when updating lines" patch.

**Comment by jvvv** [comment]
I was hoping with #43 that we could paper over the fact that the resize code needs deeper attention, then dig into it after the commandline rewrite was complete. That is obviously not going to work out. I will start working on the resize code after I get off work this afternoon.

As far as #44, that is unrelated to #42. It was just something that came to mind while I was working on #30. It is just something that I should have included in #39.

**Comment by jvvv** [comment]
xvAdjustWindows is still broken. https://github.com/martinwguy/xvi/pull/43/commits/277fc303541d30ae942713064c65723593ce1252 only fixes it for when there is only one buffer window.

**Comment by jvvv** [comment]
I have closed #44. I had thought that it was unrelated to #42. I was wrong.

**Comment by martinwguy** [comment]
This fixes the SEGV (thanks!) However, if I reduce the screen to 2 lines high and lengthen it again, the status line stays on line 2 and the rest of the screen isn't refreshed with ~'s until I say "o" - then I'm left with a ~ on line 1, the cursor on blank line 2 and the rest of the screen is OK.  Do you see the same effect at your end?

**Comment by jvvv** [comment]
I have some changes I'm working on still that haven't been pushed. There is some memory corruption going on that seems to stem from vs_resize,  but I may be mistaken. The crash point isn't always the same, so I'm still trying to track down the point of corruption. It all seems really silly and I sense that I'm being obtuse about it. I'm installing valgrind now. Hopefully that will provide more insight.

**Pull request merged**
