### PR TITLE
Bugfix: cmd_types-boundary

### PR DESCRIPTION
**Pull request by cjwagenius**

### CODE REVIEW

**Comment by cjwagenius** [comment]
Yes it does.

**Comment by martinwguy** [comment]
Sorry, yes what does what? :-?

   M

**Comment by cjwagenius** [comment]
_"Can you see if the attached also fixes the issue?"_

**Comment by martinwguy** [comment]
OK right! If you'd like the commit credited to you, can you prepare a
pull request like before?
Sorry for all this hassle, and thanks for finding and nailing this issue

Blessings

    M

**Comment by cjwagenius** [comment]
You can commit it. It's your solution. ;-)
I would have gone with my solution. Most compilers will optimize away the runtime part of it, and it's way more convenient I think.

No problems. Glad I could be of any help.

Regards

/cjw

**Comment by martinwguy** [comment]
> You can commit it. It's your solution. ;-)

Well, you found, diagnosed and fixed the issue.
I only optimized the solution for code size!

> Most compilers will optimize away the runtime part of it,

Instead they're not that good. Here are the sizes:

0 - original xvi
1 - cjw patch #1
2 - mg optimization
3 - same with enums
           text    data     bss     dec     hex filename
0        122380    9882    4584  136846   2168e src/xvi
1        122428    8058    4584  135070   20f9e src/xvi
2        122380    8042    4584  135006   20f5e src/xvi
3        122380    8042    4584  135006   20f5e src/xvi

So my nasty solution doesn't add code but saves 1840 bytes data, as
well as fixing the segfault.

> and it's way more convenient I think.

For elegance, I agree. Better data hiding (now you have to include
ascii.h before cmd.h, which fortunately it was in xvi.h) and more
robust and maintainable but hey, 1840 bytes are 1840 bytes, which is
one of xvi's targets (small memory use).

OK, I'll commit this and cite you, if you don't care about your github points :)

    M

**Comment by cjwagenius** [comment]
Look at that. You've got a good point. Thanks for sharing you thoughts about it. I certainly will have it in mind in the future.
Thanks for thinking about me, but commit it. I don't want credits for something I didn't came up with. I mostly just want to use this superb editor without segfaulting. ;-)

Regards

/cjw

**Comment by cjwagenius** [comment]
I get a 32 byte difference between our solutions with my compiler, so you're right. It doesn't get optimized out. Good to know and thanks for pointing that out.

**Comment by martinwguy** [comment]
OK! I'm using clang -Os for code size, which does better than gcc.
I'll commit your fix then, Cheers!

    M

**Comment by cjwagenius** [comment]
Yes, it looks like it. Still... It's only 64 bytes difference. It may 
be worth the tradeoff, don't you think? I mean we've saved 1776 bytes 
already.
  Enum is better otherwise. That was my first thought, but I passed it.

  Great.

  Have you noticed that it appear some random bytes (outside ASCII) out 
of nowhere in the lines now and then? I mostly use xvi in 'mchar' mode. 
I can't pin down to when it actually happens. It seems to be at random.

Regards

/cjw

  With your compiler The difference is 64 bytes
2018-01-08 11:25 skrev Martin Guy:

**Pull request closed without merging**
