### PR TITLE
Add ^C and ESC handling for cmdmode cancel and change filename completion to TAB character.

### PR DESCRIPTION
**Pull request by jvvv**
I closed #31. I could not figure out how to change the pr to point to a different branch and I wanted to revert my fork's master branch to track to your current master.

### CODE REVIEW

**Comment by martinwguy** [comment]
Looking good... I tried it on an ancient Linux (kernel 2.2.19 from
199X) without pselect and it compiles and works there too.

There is one gremlin and a couple of possible extensions:
- :ma[Ctrl-C] interrupts OK but leaves the cursor bottom right of the
screen instead of
  returning it to its position in the visual display
- [Ctrl-C] during visual insert mode should make it go back to command
mode (leaving the
  inserted characters... like ESC in visual insert mode, except that
it might also say "Interrupted" on the status line if that's not
awkward)
- [Ctrl-C] while in visual command mode should ring the bell (or flash
a visual bell) and say "Interupted". I think it should also cancel any
half-completed commands such as the first character of two-character
ones or if they have input a numeric count.

Are these do-able? Sorry to keep whipping you like this! :)

    M

**Comment by jvvv** [comment]
I'll begin work on fixing the :ma[Ctrl-C] case tonight or later tomorrow. I'll start poking at the others, also; probably in conjunction with the fix. These look like reasonable usages to me and comparable to what would be expected. Thanks for your input.

I don't mind reworking this. Besides, I respect the way you are keeping the bigger picture in focus. No worries.

**Comment by martinwguy** [comment]
A tiny addition: this is required to define struct timeval on old Linuces otherwise compilation fails with "unix.c:219: storage size of `tv' isn't known".

```
--- a/src/unix.c
+++ b/src/unix.c
@@ -54,5 +54,6 @@ FILE *fdopen(int fd, const char *mode);
 #ifdef  POSIX
 #      include <unistd.h>
 #      include <sys/types.h>
 #      include <sys/wait.h>
+#      include <sys/time.h>
 #endif
 ```

**Comment by jvvv** [comment]
Could you try this instead? This isn't what is actually needed, but I'm trying to find an older copy of the posix spec (circa linux libc5 days), so that a more appropriate conditional can be used (one that tests _POSIX_SOURCE and _POSIX_C_SOURCE, but with relevent values, so that systems that conform to older posix will have the correct include, not just linux libc5). Use of <sys/time.h> for select() was superceded with <sys/select.h>, but I'm trying to figure out at which version of the spec.

--- a/src/unix.c
+++ b/src/unix.c
@@ -57,6 +57,12 @@ FILE *fdopen(int fd, const char *mode);
 #      include <sys/wait.h>
 #endif
 
+#if defined  __GNU_LIBRARY__ && __GNU_LIBRARY__ == 1
+#include       <sys/time.h>
+#else
+#include       <sys/select.h>
+#endif
+
 #if defined(sun) && !defined(POSIX)
 #   ifndef TERMIOS
 #      define  TERMIOS

**Comment by jvvv** [comment]
A better feature test would be something like:
[code]
#if defined _POSIX_C_SOURCE && _POSIX_C_SOURCE > 1
#include <sys/select.h>
#else
#include <sys/time.h>
[/code]

I'd like to verify the _POSIX_C_SOURCE value before pushing the change.

**Comment by martinwguy** [comment]
I just follow the notes in the manual pages for feature tests, but
anyway they are glibc-sspecific, i.e. if you have glibc and it's this
version then it will work... but it might work with other systems,
from BSDi to AIX to Xenix-386 to SunOS (pre-Solaris) to Unix V7. I
remember when select() was invented, with VAX BSD4.2 in 1984 or so...
but I think you'd be hard put to find a VAX BSD 4.1 system these
days... maybe among the last PDP-11 Unices?

I was fortunate (?) enough to grow up while it was still chaotic and
you just had to try it on each system and see what worked, however,
one of xvi's main goals is to be super-portable, which means using the
bare minimum that is likely to work most places.

However, it's becoming hard to find the many systems on which xvi has
been known to work.  There's an ancient Linux system (he of the "needs
sys/time.h") if you ssh to luther@medialab.freaknet.org password
luther  Those guys run a working ancient computer museum so for next
release I should really do some portability testing and see if they
have, like old AIXes or Xenix-386 or HPUX or whatever.

Cheers

    M

**Pull request merged**
